# Generated by Django 3.2.4 on 2022-05-11 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('primary_number', models.IntegerField(max_length=10)),
                ('country_code', models.IntegerField(max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('login_status', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('primary_number', models.IntegerField(max_length=10)),
                ('country_code', models.IntegerField(max_length=5)),
                ('basic_info_status', models.BooleanField()),
                ('medical_info_status', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('filtering_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accountholder')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('paid_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('open', 'Open')], max_length=10)),
                ('payment_date', models.DateField()),
                ('filtering_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accountholder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('canceled', 'Canceled')], max_length=10)),
                ('payment_date', models.DateField()),
                ('filtering_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accountholder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
            ],
        ),
    ]
