# Generated by Django 3.2.4 on 2022-05-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='country_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='primary_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='country_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='primary_number',
            field=models.IntegerField(),
        ),
    ]
